// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-accounts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_accounts_default = defineTool({
  name: "list_accounts",
  title: "List accounts",
  description: "List all financial accounts (bank, cash, card, crypto) for the signed-in user, including institution, currency and source.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client(ctx).from("accounts").select("id, name, institution, currency, type, source, is_archived").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { accounts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-transactions.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_transactions_default = defineTool2({
  name: "list_transactions",
  title: "List transactions",
  description: "List transactions for the signed-in user, optionally filtered by date range or merchant substring. Returns up to `limit` rows (default 50, max 500) sorted newest first.",
  inputSchema: {
    since: z.string().optional().describe("Inclusive start date (YYYY-MM-DD)."),
    until: z.string().optional().describe("Inclusive end date (YYYY-MM-DD)."),
    merchant_contains: z.string().optional().describe("Case-insensitive substring to match against merchant or description."),
    limit: z.number().int().min(1).max(500).optional().describe("Max rows to return. Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ since, until, merchant_contains, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = client2(ctx).from("transactions").select("id, date, description, merchant, amount, currency, category_id, subcategory_id, account_id, is_subscription").order("date", { ascending: false }).limit(limit ?? 50);
    if (since) q = q.gte("date", since);
    if (until) q = q.lte("date", until);
    if (merchant_contains) q = q.or(`merchant.ilike.%${merchant_contains}%,description.ilike.%${merchant_contains}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "List categories",
  description: "List spending categories and their subcategories for the signed-in user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = client3(ctx);
    const [cats, subs] = await Promise.all([
      sb.from("categories").select("id, name, kind, color, icon").order("name"),
      sb.from("subcategories").select("id, name, category_id").order("name")
    ]);
    if (cats.error) return { content: [{ type: "text", text: cats.error.message }], isError: true };
    if (subs.error) return { content: [{ type: "text", text: subs.error.message }], isError: true };
    const payload = { categories: cats.data ?? [], subcategories: subs.data ?? [] };
    return { content: [{ type: "text", text: JSON.stringify(payload, null, 2) }], structuredContent: payload };
  }
});

// src/lib/mcp/tools/list-recurring.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
function client4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recurring_default = defineTool4({
  name: "list_recurring_expenses",
  title: "List recurring expenses",
  description: "List subscriptions and other recurring expenses for the signed-in user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client4(ctx).from("recurring_expenses").select("id, name, amount, currency, frequency, category_id, type, subtype, next_due_date, is_active").order("next_due_date", { ascending: true, nullsFirst: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: { recurring: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-budgets.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function client5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_budgets_default = defineTool5({
  name: "list_budgets",
  title: "List budgets",
  description: "List monthly per-category budget limits for the signed-in user, optionally scoped to a specific month (YYYY-MM).",
  inputSchema: {
    month: z2.string().optional().describe("Month in YYYY-MM format. Omit to return all budgets.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ month }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = client5(ctx).from("budgets").select("id, category_id, subcategory_id, month, amount, currency");
    if (month) q = q.eq("month", month);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: { budgets: data ?? [] } };
  }
});

// src/lib/mcp/tools/create-transaction.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function client6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_transaction_default = defineTool6({
  name: "create_transaction",
  title: "Create transaction",
  description: "Create a new transaction (expense or income) for the signed-in user. Amount is negative for expenses, positive for income.",
  inputSchema: {
    date: z3.string().describe("Transaction date, YYYY-MM-DD."),
    amount: z3.number().describe("Signed amount. Negative for expenses, positive for income."),
    currency: z3.string().describe("ISO currency code, e.g. USD, ARS, EUR."),
    description: z3.string().describe("Human-readable description."),
    merchant: z3.string().optional().describe("Merchant name."),
    account_id: z3.string().optional().describe("Account UUID this transaction belongs to."),
    category_id: z3.string().optional().describe("Category UUID."),
    subcategory_id: z3.string().optional().describe("Subcategory UUID.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client6(ctx).from("transactions").insert({ ...input, user_id: ctx.getUserId() }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Created transaction ${data.id}` }], structuredContent: { transaction: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "izkjttswwcsjjlhbicow";
var mcp_default = defineMcp({
  name: "my-money-compass-mcp",
  title: "My Money Compass",
  version: "0.1.0",
  instructions: "Personal finance tools for My Money Compass. Read the signed-in user's accounts, transactions, categories, recurring expenses, and budgets, or create a new transaction. All data is scoped to the authenticated user via Supabase RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_accounts_default, list_transactions_default, list_categories_default, list_recurring_default, list_budgets_default, create_transaction_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
